describe('Radio bill', function(){
it ('Should return the total call cost ', function(){
var init = radioBtnFactory()
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
assert.equal(11.00, init.getCallCost())
assert.equal(11.00, init.getCostTotal())
})
it('Should return the total sms cost', function(){
var init = radioBtnFactory()
init.radioBtnBill('sms')
init.radioBtnBill('sms')
init.radioBtnBill('sms')
assert.equal(2.25, init.getSmsCost())
assert.equal(2.25, init.getCostTotal())
})
it('Should return the total cost for call and sms', function(){
var init = radioBtnFactory()
init.radioBtnBill('sms')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('sms')
init.radioBtnBill('call')
assert.equal(8.25, init.getCallCost())
assert.equal(1.50, init.getSmsCost())
assert.equal(9.75, init.getCostTotal())
})
it('Should change colour to Orange when total cost is greater than 20',function(){
var init = radioBtnFactory()
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('sms')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('sms')
init.radioBtnBill('call')
assert.equal(29.00, init.getCostTotal())
})
it('Should change colour to Red when total cost is greater than 30 ',function(){
var init = radioBtnFactory()
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
init.radioBtnBill('call')
assert.equal(55.00, init.getCostTotal())
})
})